csp_observer/urls.py
from django.urls import path
from . import views
from .update import update_rules

urlpatterns = [
    # business logic
    path('report/<str:report_type>/<uuid:session_id>', views.report, name='report'),
    path('result/<uuid:session_id>', views.result, name='result'),
    path('resultdetail/<uuid:session_id>', views.result_detail, name='result_detail'),
    path('master/session/<uuid:session_id>', views.master_session, name='master_session'),
    path('session/<uuid:session_id>/share', views.share_session, name='share_session'),

    # admin
    path('admin/', views.admin, name='admin'),
    path('admin/update/rules/', views.admin_update_rules, name='admin_update_rules'),
    path('admin/rule/<int:rule_id>/delete', views.delete_custom_rule, name='delete_custom_rule'),
    path('chart/observed_rule_distribution', views.chart_observed_rule_distribution, name='chart_observed_rule_distribution'),
    path('chart/reports_per_day', views.chart_reports_per_day, name='chart_reports_per_day'),

    # other
    path('privacy/', views.privacy, name='privacy'),
]

csp_observer/models.py
import uuid
from django.db import models
from .managers import CspRuleManager

class Session(models.Model):
    """Represents a single user session (a page access)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_agent = models.CharField(max_length=255)
    anonymized_ip = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}@{}".format(self.id, self.created_at)

class CspRule(models.Model):
    """Represents a rule for evaluation of csp errors or whitelisting."""
    CAUSES = (
        ('extension', 'Browser Extension'),
        ('browser', 'Web Browser'),
        ('malware', 'Malware'),
        ('other', 'Other'),
    )

    global_id = models.CharField(max_length=255, blank=True, null=True)
    blocked_url = models.CharField(max_length=255, blank=True, null=True)
    effective_directive = models.CharField(max_length=255, blank=True, null=True)
    ignore = models.BooleanField(default=False)
    title = models.CharField(max_length=255, blank=True, null=True)
    short_description = models.TextField(blank=True, null=True)
    long_description = models.TextField(blank=True, null=True)
    cause = models.CharField(max_length=255, choices=CAUSES, default='other')

    objects = CspRuleManager()

    def __str__(self):
        return "{} {} ({}) {}".format(self.global_id if self.global_id else "", self.title, self.blocked_url, "[Ignore]" if self.ignore else "")

class CspReport(models.Model):
    """CSP Report model.

    Follows the new CSPViolationReportBody (https://w3c.github.io/webappsec-csp/#cspviolationreportbody)
    """
    session = models.ForeignKey(Session, to_field="id", on_delete=models.CASCADE)
    document_url = models.CharField(max_length=255)
    referrer = models.CharField(max_length=255, blank=True, null=True)
    blocked_url = models.CharField(max_length=255, blank=True, null=True)
    effective_directive = models.CharField(max_length=255)
    original_policy = models.CharField(max_length=255, blank=True, null=True)
    source_file = models.CharField(max_length=255, blank=True, null=True)
    sample = models.CharField(max_length=255, blank=True, null=True)
    disposition = models.CharField(max_length=255, blank=True, null=True)
    status_code = models.IntegerField(blank=True, null=True)
    line_number = models.IntegerField(blank=True, null=True)
    column_number = models.IntegerField(blank=True, null=True)
    matching_rules = models.ManyToManyField(CspRule, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}@{}".format(self.blocked_url, self.session)

class StoredConfig(models.Model):
    """Generic model for storing key/value pairs."""
    key = models.TextField(unique=True)
    value = models.TextField(blank=True, null=True)

    def __str__(self):
        return "{}={}".format(self.key, self.value)

csp_observer/templates/client_ui/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/clientui.css' %}">
<script language="javascript" type="text/javascript" src="{% static 'js/clientui.js' %}"></script>
<script language="javascript" type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(){
        var userInterface = new CSPObserverUserInterface({
            'sessionId': '{{ session_id }}',
            'visibility': '{{ visibility }}'
        });
        userInterface.init();
    });
</script>
<div id="cspo-clientui">
    <div class="clientui-header">
        <p class="clientui-title">Browser Extension Scan</p>
        <button class="close" aria-label="close" @click="close">x</button>
    </div>
    <div class="clientui-body">
        <div class="status">
            <div class="icon">
                <div class="spinner">
                    <div class="double-bounce1"></div>
                    <div class="double-bounce2"></div>
                </div>
            </div>
            <div class="content">
                <span class="scanning">
                    Observing browser behavior...
                </span>
            </div>
        </div>
        <hr>
        <p class="help">CSP Observer is securely scanning your browser's activity to detect malicious extensions.</p>
    </div>
</div>

csp_observer/templates/client_ui/popup.html
{% load static %}
<link rel="stylesheet" href="{% static 'csp_observer/css/clientui.css' %}">
<script language="javascript" type="text/javascript" src="{% static 'csp_observer/js/clientui.js' %}"></script>
<script language="javascript" type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(){
        var userInterface = new CSPObserverUserInterface({
            'sessionId': '{{ session_id }}',
            'visibility': '{{ visibility }}',
            'resultUri': '{{ result_uri}}',
            'detailpageUri': '{{ detailpage_uri }}'
        });
        userInterface.init();
    });
</script>
<div id="cspo-clientui">
    <div class="clientui-header">
        <p class="clientui-title">Browser Extension Scan</p>
        <button class="close" aria-label="close" @click="close">x</button>
    </div>
    <div class="clientui-body">
        <div class="status">
            <div class="icon">
                <img id="cspo-icon-alert" class="result-icon" src="{% static 'csp_observer/img/alert-circle.svg' %}" alt="Image showing a warning symbol">
                <img id="cspo-icon-check" class="result-icon" src="{% static 'csp_observer/img/check-circle.svg' %}" alt="Image showing a checkmark symbol">
                <div id="cspo-icon-spinner" class="result-icon spinner">
                    <div class="double-bounce1"></div>
                    <div class="double-bounce2"></div>
                </div>
            </div>
            <div class="content">
                <p id="cspo-status-message">
                    Clientui not initialized
                </p>
            </div>
        </div>
        <div class="spoiler">
            <p class="help">
                <img id="cspo-icon" width="50" src="{% static 'csp_observer/img/cspo-logo-64px.png' %}" alt="The CSP Observer Logo: A small telescope with the letter CSP above it.">
                
                <a href="https://github.com/flxn/django-csp-observer" target="_blank" rel="noopener nofollow noreferrer">CSP Observer</a> is passively scanning your browser's activity to detect malicious extensions.<br />
                Your privacy is our top priority <a href="{% url 'privacy' %}" target="_blank">click here to learn about our privacy policy</a>.
            </p>
        </div>
        
    </div>
</div>

csp_observer/templates/client_ui/privacy.html
{% extends 'cspo_base.html' %}
{% load static %}

{% block title %}Privacy Policy{% endblock title %}

{% block content %}
<div class="container">
    <h1>Privacy Policy</h1>
    <h2>Placeholder Page</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus alias fugiat, porro nobis id ex est nam voluptate officia, laborum fuga eum aperiam ea facilis mollitia neque accusantium nihil qui.</p>
</div>
{% endblock content %}

csp_observer/templates/client_ui/result_detail.html
{% extends 'cspo_base.html' %}
{% load static %}

{% block title %}Scan Result{% endblock title %}

{% block content %}

<script>
    window.shareSessionUrl = '{% url "share_session" session.id %}';
</script>

<div class="container">
    <img id="cspo-icon" src="{% static 'csp_observer/img/cspo-logo-256px.png' %}" alt="The CSP Observer Logo: A small telescope with the letter CSP above it.">
    <h1>Scan Report</h1>
    <h3>We have detected {{rules|length }} possible issue{{rules|length|pluralize}} with your web browser.</h2>
    <div class="mt-5">
        {% for rule in rules.values %}
        <div class="card mt-3">
            <div class="card-header">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-info-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM8 5.5a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                  </svg>
                  {{rule.title}}
            </div>
            <div class="card-body">
            <a href="https://github.com/flxn/csp-observer-data/blob/master/rules/{{rule.global_id}}.md" target="_blank" class="float-right">View In Database</a>
            <h5 class="card-title">{{ rule.short_description }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Probably caused by: {{ rule.get_cause_display }}</h6>
            <p class="card-text">
                <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-header" id="heading{{rule.global_id}}">
                        <h2 class="mb-0">
                            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{rule.global_id}}" aria-expanded="true" aria-controls="collapse{{rule.global_id}}">
                                <svg class="if-collapsed" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                                </svg>
                                <svg class="if-not-collapsed" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                                </svg>
                                View details about this detection
                            </button>
                            
                        </h2>
                        </div>
                    
                        <div id="collapse{{rule.global_id}}" class="collapse" aria-labelledby="heading{{rule.global_id}}" data-parent="#accordionExample">
                        <div class="card-body">
                            {{rule.long_description | safe}}
                        </div>
                        </div>
                    </div>
                </div>
            </p>
            </div>
        </div>
        {% endfor %}
    </div>

    <hr>

    {% if other_reports|length > 0 %}
        <h3>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-question-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.57 6.033H5.25C5.22 4.147 6.68 3.5 8.006 3.5c1.397 0 2.673.73 2.673 2.24 0 1.08-.635 1.594-1.244 2.057-.737.559-1.01.768-1.01 1.486v.355H7.117l-.007-.463c-.038-.927.495-1.498 1.168-1.987.59-.444.965-.736.965-1.371 0-.825-.628-1.168-1.314-1.168-.901 0-1.358.603-1.358 1.384zm1.251 6.443c-.584 0-1.009-.394-1.009-.927 0-.552.425-.94 1.01-.94.609 0 1.028.388 1.028.94 0 .533-.42.927-1.029.927z"/>
            </svg> We also detected {{other_reports|length}} unknown request{{other_reports|length|pluralize}} from your browser.
        </h3>
        <p>
            This service relies on voluntary data from the community for analysis. 
            <br/>You can help us to improve our detection by sharing your data and help improve the privacy of all other users.
        </p>

        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-header" id="heading-share-data-session">
                <h2 class="mb-0">
                    <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse-share-data-session" aria-expanded="true" aria-controls="collapse-share-data-session">
                        <svg class="if-collapsed" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                        </svg>
                        <svg class="if-not-collapsed" width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-down" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                        </svg>
                        View the data that will be shared
                    </button>
                    
                </h2>
                </div>
            
                <div id="collapse-share-data-session" class="collapse" aria-labelledby="heading-share-data-session" data-parent="#accordionExample">
                <div class="card-body">
                    <code>{{shared_data}}</code>
                </div>
                </div>
            </div>
        </div>
        <br>

        <p>Do you agree to share this data with us?</p>
        <button class="btn btn-success" onclick="shareSessionData('{{session.id}}')">Yes, I agree</button>
        <div id="share-data-response" class="alert mt-3" role="alert" style="display: none;"></div>
    {% endif %}
</div>


{% endblock content %}